---
title: "Cardiomycytes RNA analysis volcano plot"
output: pdf_document
date: '2023-04-06'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
```
``` { r } 
ICD <- read.csv ("ALLgenenew.csv")
volcano <- ggplot(ICD, aes(x = b, y = -log10(qval.x))) +
+     geom_point(alpha = 0.5, size = 2) + scale_color_gradient2(midpoint = 0, low = "blue", mid = "white", high = "red") + labs(color = "b") + guides(color = guide_colorbar(title.position = "top", direction = "horizontal")) +
+     geom_hline(yintercept = -log10(0.05), linetype = "dashed", color = "yellow") +
+     geom_vline(xintercept = c(-1, 1), linetype = "dashed", color = "yellow") +
+     labs(x = "Fold change", y = "-log10(p-value)") +
+     ggtitle("Volcano plot")
> print(volcano)
```
This code above will give a good volcano plot however; Even I program it to have differnet color but it seems this doesn't work.
to add gene names this code used however the gene names added to the background whihc make it unreadable; I wil try make it in a way that genes appear once you click  on dots if that is possible
the code below for add gene name
``` {r}
volcano <- ggplot(ICD, aes(x = b, y = -log10(qval.x))) +
+     geom_point(alpha = 0.5, size = 2) + scale_color_gradient2(midpoint = 0, low = "blue", mid = "white", high = "red") + labs(color = "b") + guides(color = guide_colorbar(title.position = "top", direction = "horizontal")) +
+     geom_hline(yintercept = -log10(0.05), linetype = "dashed", color = "yellow") +
+     geom_vline(xintercept = c(-1, 1), linetype = "dashed", color = "yellow") +
+     labs(x = "Fold change", y = "-log10(p-value)") +
+     ggtitle("Volcano plot")
volcano <- volcano + geom_text(aes(label = ext_gene.x), hjust = 0, vjust = 0, size = 3, color = "black")
> print(volcano)
```

